-- Criação da Tabela PRODUTO
CREATE TABLE PRODUTO (
    ID INT AUTO_INCREMENT NOT NULL,
    DESCRICAO VARCHAR(250),
    PRECO_COMPRA DECIMAL(25, 16),
    PRECO_VENDA DECIMAL(25, 16),
    DATA_CADASTRO TIMESTAMP,
    PRIMARY KEY (ID)
);


-- Criação da Tabela PRODUTO_IMAGEM
CREATE TABLE PRODUTO_IMAGEM (
    ID INT AUTO_INCREMENT NOT NULL,
    PRODUTO_ID INT NOT NULL,
    PRINCIPAL BOOLEAN,
    URI_IMAGEM VARCHAR(300),
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);
